# Use root/example as user/password credentials
version: "3"

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: catcallsmock
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
